### ISSUE TITLE
SVLEN should be Integer and not String for VCF files nstd167 (HG002) and nstd137 (CHM1_CHM13)

### ISSUE THREAD

**Issue by lsantuari** [GooglingTheCancerGenome/notebooks#3]
It should be:

`##INFO=<ID=SVLEN,Number=.,Type=Integer,Description="Difference in length between REF and ALT alleles">`

instead of:

`##INFO=<ID=SVLEN,Number=.,Type=String,Description="Difference in length between REF and ALT alleles">`

otherwise it raises an error with StructuralVariantAnnotation.

**Comment by arnikz** [comment]
Please include the error msg and the code line(s) you're referring to.

**Comment by arnikz** [comment]
Fixed in https://github.com/GooglingTheCancerGenome/notebooks/commit/9e383485ab2fdf9d8205d910c2247332a670dba1
